### ISSUE TITLE
数据获取

### ISSUE THREAD

**Issue by BestCoderXQX** [haodynasty/AndroidBleManager#1]
大佬  多设备连接同时获取数据

**Comment by BestCoderXQX** [comment]
现在同时连接实现了 ，但是获取数据这一块 ，有没有详细点的流程，看文档没实现出来

**Comment by haodynasty** [comment]
> 现在同时连接实现了 ，但是获取数据这一块 ，有没有详细点的流程，看文档没实现出来
@BestCoderXQX 
多设备连接后获取数据和单个设备是一样的，调用MultiConnectManager的setBluetoothGattCallback在回调方法中可以区分哪个设备并进行数据处理
