### ISSUE TITLE
导入android studio 出错

### ISSUE THREAD

**Issue by lingyun0129** [haodynasty/AndroidBleManager#2]
Error:Could not find im.fir:gradle-fir-publisher:1.0.7.
Searched in the following locations:
    file:/E:/Android/Android Studio/gradle/m2repository/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.pom
    file:/E:/Android/Android Studio/gradle/m2repository/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.jar
    https://jcenter.bintray.com/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.pom
    https://jcenter.bintray.com/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.jar
    https://plugins.gradle.org/m2/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.pom
    https://plugins.gradle.org/m2/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.jar
    http://maven.bughd.com/public/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.pom
    http://maven.bughd.com/public/im/fir/gradle-fir-publisher/1.0.7/gradle-fir-publisher-1.0.7.jar
Required by:
    project :

**Comment by haodynasty** [comment]
@lingyun0129 fir插件不小心被fir.im公司给移除了，你只需要把该插件删除即可，我项目稍后也会更新

**Comment by haodynasty** [comment]
@lingyun0129 已经更新工程，去除了fir

**Comment by lingyun0129** [comment]
@haodynasty 还有错Error:(23, 0) Build Config field cannot have a null parameter
<a href="openFile:E:\workspace\AndroidBleManager\app\build.gradle">Open File</a>
app\build.gradle  line 23
。。。。。。。。。。。。。。。。。。。。。。。。
        buildConfigField "String", "FIR_TOKEN", hasLocalProperty("FIR_TOKEN_STRING") ? getLocalProperty("FIR_TOKEN_STRING") : System.getenv("FIR_TOKEN")
        buildConfigField "String", "FIR_ID", hasLocalProperty("FIR_ID_STRING") ? getLocalProperty("FIR_ID_STRING") : System.getenv("FIR_ID")
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
